repos:
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.5.0
    hooks:
      - id: gdlint
        name: gdlint
        exclude: ^topdown/addons/
      - id: gdformat
        name: gdformat (check only)
        args: ["--check"]
        exclude: ^topdown/addons/
